services:
  - type: web
    name: user-registration-api
    runtime: node
    rootDir: ./server
    buildCommand: npm ci && npm run build
    startCommand: node dist/main
    plan: free
    autoDeploy: true
    env: node
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        value: mongodb+srv://admin:Minhanh123.@cluster0.xasxqa4.mongodb.net/user-registration?retryWrites=true&w=majority&appName=Cluster0
      - key: FRONTEND_URL
        value: https://user-registration-ia06.vercel.app
    healthCheckPath: /health